### ISSUE TITLE
First headline caption not showing on pageload

### ISSUE THREAD

**Issue by djjshelley** [CSS-Tricks/AnythingSlider#638] opened 2015-02-19 19:21 UTC
Hello, I've ran anythingslider for a while and one day the initial caption stopped showing, I'm stumped. I tried updating everything but it blew up.

Feel free to checkout the code here:
http://www.aldershotaudiology.com/

Thanks!

Josiah

**Comment by Mottie** [comment] 2015-02-19 20:01
Hi Josiah!

Hmm, that is an odd error to see.

Would you please try to move the AnythingSlider initialization code block to the bottom of the page and see if that solves the problem.

**Comment by djjshelley** [comment] 2015-02-19 20:14
I’ve added it to the bottom and I’m not finding any difference.

Thanks for helping me out!

Josiah

**Comment by Mottie** [comment] 2015-02-19 20:22
Oh, could you try the latest version. I see you're using v1.5.18 and the current version is 1.9.4. The fx file also has an update available.

**Comment by djjshelley** [comment] 2015-02-19 20:24
I did update to the latest version but didn’t have any luck. In fact, it kind of blew up the slide selection menu. Probably because of the css used. I created this site about 4 years ago I’d say.

Josiah

**Comment by Mottie** [comment] 2015-02-19 20:41
Hmm, ok I guess the next thing to try is this... the first line of code:

```js
$(function () {
$('#slider').anythingSlider({
```

change that to:

```js
$(window).load(function () {
$('#slider').anythingSlider({
```

**Comment by djjshelley** [comment] 2015-02-19 20:43
Tried it at the top and bottom of the page, no luck.

**Comment by Mottie** [comment] 2015-02-19 21:26
Hmm, a tough one...

Well first off, you might want to change that back LOL. The images stacked on top of each other is distracting ;)

The problem I am seeing is that there is an error on the page caused by the fx code.  For some reason it isn't recognizing that AnythingSlider is already initialized. So I think separating the code like this might help \*crosses fingers\*

```js
$(function () {
	$('#slider').anythingSlider({
		height          : '415',
		expand          : true,
		delay           : 7000,
		startStopped    : false,
		resizeContents  : true,
		pauseOnHover    : true,
		buildArrows     : false,
		InfinitiveSlides: false,
		autoPlayLocked  : true, // If true, user changing slides will not stop the slideshow
		navigationFormatter : function(i, panel){
			// Add Preview Items here
			return '<img src="img/pictures/slider/slider-item-' + ['1', '2', '3', '4'][i - 1] + '-thumb.jpg">';
		}
	});

	$(".thumbNav").hide();

	//Slider Controls - external
	$('#slider-wrapper').hover(function() {
		$(".slideforward").stop(true, true).fadeIn();
		$(".slidebackward").stop(true, true).fadeIn();
		$(".thumbNav").stop(true, true).fadeIn();
	}, function() {
		$(".slideforward").fadeOut();
		$(".slidebackward").fadeOut();
		$(".thumbNav").fadeOut();
	});

	$(".slideforward").click(function(){
		$('#slider').data('AnythingSlider').goForward();
	});

	$(".slidebackward").click(function(){
		$('#slider').data('AnythingSlider').goBack();
	});
});

$(window).load(function(){
	$('#slider').anythingSliderFx({
		'.slider-caption-top'    : [ 'caption-Top', '300px', '400', 'easeOutExpo' ],
		'.slider-caption-left'    : [ 'caption-Left', '300px', '400', 'easeInQuad' ],
		'.slider-caption-right'    : [ 'caption-Right', '300px', '400', 'easeInQuad' ],
		'.slider-caption-bottom'    : [ 'caption-Bottom', '300px', '400', 'easeOutExpo' ]
	});
});
```

**Comment by djjshelley** [comment] 2015-02-19 21:30
Can’t go wrong with a challenge.

I switched it, no affect on the website. I also tried it at the bottom of the page.

Josiah

**Comment by Mottie** [comment] 2015-02-19 21:46
Oh, ok I think I see the problem now!

if you look at line 99, you'll see a lonely `$(this)`:

```js
$(this)

	// bind events for "OUT" effects - occur when leaving a page
	.bind('slide_init', function(e, slider){
```

change it to

```js
var base = $(this)
```


You'll see that it is [set this way in the latest fx code version](https://github.com/CSS-Tricks/AnythingSlider/blob/master/js/jquery.anythingslider.fx.js#L112)

Then you should be able to go back to your original code (sorry!)

```js
$(function () {
	$('#slider').anythingSlider({
		height          : '415',
		expand          : true,
		delay           : 7000,
		startStopped    : false,
		resizeContents  : true,
		pauseOnHover    : true,
		buildArrows     : false,
		InfinitiveSlides: false,
		autoPlayLocked  : true, // If true, user changing slides will not stop the slideshow
		navigationFormatter : function(i, panel){
			// Add Preview Items here
			return '<img src="img/pictures/slider/slider-item-' + ['1', '2', '3', '4'][i - 1] + '-thumb.jpg">';
		}
	}).anythingSliderFx({
		'.slider-caption-top'    : [ 'caption-Top', '300px', '400', 'easeOutExpo' ],
		'.slider-caption-left'   : [ 'caption-Left', '300px', '400', 'easeInQuad' ],
		'.slider-caption-right'  : [ 'caption-Right', '300px', '400', 'easeInQuad' ],
		'.slider-caption-bottom' : [ 'caption-Bottom', '300px', '400', 'easeOutExpo' ]
	});

	$(".thumbNav").hide();

	//Slider Controls - external
	$('#slider-wrapper').hover(function() {
		$(".slideforward").stop(true, true).fadeIn();
		$(".slidebackward").stop(true, true).fadeIn();
		$(".thumbNav").stop(true, true).fadeIn();
	}, function() {
		$(".slideforward").fadeOut();
		$(".slidebackward").fadeOut();
		$(".thumbNav").fadeOut();
	});

	$(".slideforward").click(function(){
		$('#slider').data('AnythingSlider').goForward();
	});

	$(".slidebackward").click(function(){
		$('#slider').data('AnythingSlider').goBack();
	});
});
```

**Comment by djjshelley** [comment] 2015-02-19 21:52
Hmm…. thank you for all your help but I’m still seeing the issue… I’ve updated line 99 of anythingslider.fx.

Am I missing an update?

Josiah

**Comment by Mottie** [comment] 2015-02-19 22:07
\*smack head\*

We're also missing the part from [line 181](https://github.com/CSS-Tricks/AnythingSlider/blob/master/js/jquery.anythingslider.fx.js#L181):

Sorry, I have way too many distractions at the moment.

So, change this code in the fx file from this:

```js
			});
			
			// call gotoPage to trigger intro animation
			$(window).load(function(){ base.gotoPage(base.currentPage, base.playing); });
```

to this:

```js
			}).data('AnythingSlider');
			
			// call gotoPage to trigger intro animation
			$(window).load(function(){ base.gotoPage(base.currentPage, base.playing); });
```

And yes, this could "probably" have been fixed by updating to the latest ["jquery.anythingslider.fx.js" file](https://github.com/CSS-Tricks/AnythingSlider/blob/master/js/jquery.anythingslider.fx.js).

**Comment by djjshelley** [comment] 2015-02-19 22:20
Success!!! Thank you so much!!

**Comment by Mottie** [comment] 2015-02-19 22:21
YAY! you're welcome... \*whew\*

**Closed** 2016-05-02 19:01 UTC
Labels: How to..., Question
